version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - 's6r-network'
  kafka:
    build: .
    ports:
      - "9092:9092"
    networks:
      - 's6r-network'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "mails:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  s6r-network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"