//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.apress.spring6recipes.weather.schemas;

import jakarta.annotation.Generated;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;

import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="TemperatureInfo" maxOccurs="5">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="min" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   <element name="max" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   <element name="average" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                 </sequence>
 *                 <attribute name="city" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 <attribute name="date" type="{http://www.w3.org/2001/XMLSchema}date" />
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "temperatureInfo"
})
@XmlRootElement(name = "GetTemperaturesResponse")
@Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v3.0.0", date = "2022-09-27T20:05:13+02:00")
public class GetTemperaturesResponse {

    @XmlElement(name = "TemperatureInfo", required = true)
    protected List<TemperatureInfo> temperatureInfo;

    /**
     * Gets the value of the temperatureInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the temperatureInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTemperatureInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TemperatureInfo }
     * 
     * 
     * @return
     *     The value of the temperatureInfo property.
     */
    public List<TemperatureInfo> getTemperatureInfo() {
        if (temperatureInfo == null) {
            temperatureInfo = new ArrayList<>();
        }
        return this.temperatureInfo;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="min" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         <element name="max" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         <element name="average" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *       </sequence>
     *       <attribute name="city" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       <attribute name="date" type="{http://www.w3.org/2001/XMLSchema}date" />
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "min",
        "max",
        "average"
    })
    public static class TemperatureInfo {

        protected double min;
        protected double max;
        protected double average;
        @XmlAttribute(name = "city")
        protected String city;
        @XmlAttribute(name = "date")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar date;

        /**
         * Gets the value of the min property.
         * 
         */
        public double getMin() {
            return min;
        }

        /**
         * Sets the value of the min property.
         * 
         */
        public void setMin(double value) {
            this.min = value;
        }

        /**
         * Gets the value of the max property.
         * 
         */
        public double getMax() {
            return max;
        }

        /**
         * Sets the value of the max property.
         * 
         */
        public void setMax(double value) {
            this.max = value;
        }

        /**
         * Gets the value of the average property.
         * 
         */
        public double getAverage() {
            return average;
        }

        /**
         * Sets the value of the average property.
         * 
         */
        public void setAverage(double value) {
            this.average = value;
        }

        /**
         * Gets the value of the city property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCity() {
            return city;
        }

        /**
         * Sets the value of the city property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCity(String value) {
            this.city = value;
        }

        /**
         * Gets the value of the date property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDate(XMLGregorianCalendar value) {
            this.date = value;
        }

    }

}
