//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.apress.spring6recipes.weather.schemas;

import jakarta.annotation.Generated;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.apress.spring6recipes.weather.schemas package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
@Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v3.0.0", date = "2022-09-27T20:05:13+02:00")
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.apress.spring6recipes.weather.schemas
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetTemperaturesResponse }
     * 
     * @return
     *     the new instance of {@link GetTemperaturesResponse }
     */
    public GetTemperaturesResponse createGetTemperaturesResponse() {
        return new GetTemperaturesResponse();
    }

    /**
     * Create an instance of {@link GetTemperaturesRequest }
     * 
     * @return
     *     the new instance of {@link GetTemperaturesRequest }
     */
    public GetTemperaturesRequest createGetTemperaturesRequest() {
        return new GetTemperaturesRequest();
    }

    /**
     * Create an instance of {@link GetTemperaturesResponse.TemperatureInfo }
     * 
     * @return
     *     the new instance of {@link GetTemperaturesResponse.TemperatureInfo }
     */
    public GetTemperaturesResponse.TemperatureInfo createGetTemperaturesResponseTemperatureInfo() {
        return new GetTemperaturesResponse.TemperatureInfo();
    }

}
