//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://spring6recipes.apress.com/weather/schemas", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.apress.spring6recipes.weather.schemas;
